Simplify running simulations
boriskaus/MagmaThermoKinematics.jl pull request #7
Opened 2023-12-06 22:21 UTC by boriskaus

The current way to perform a simulation is a bit complicated, and not easily customisable. 

With this PR, we simplify that. The basic idea is that we have a single 2D code, `MTK_GeoParams_2D` that runs the main simulation:

```Julia
Grid, Arrays, Tracers, Dikes, time_props = MTK_GeoParams_2D(MatParam::Tuple, Num::NumParam, Dike_params::DikeParam); 
```
The input are the material parameters (from `GeoParams`) and two structures in which we specify the numerical parameters and the dike parameters. 

Within `MTK_GeoParams_2D` we have a number of callback functions:
```Julia
        # Add new dike every X years -----------------
        Tracers = MTK_inject_dikes(Grid, Num, Arrays, Mat_tup, Dikes, Tracers, dike, Tnew_cpu)
        # --------------------------------------------

        # Update time-dependent properties -----------
        MTK_update_TimeDepProps!(time_props, Grid, Num, Arrays, Mat_tup, Dikes)
        # --------------------------------------------

        # Visualize results --------------------------
        MTK_visualize_output(Grid, Num, Arrays, Mat_tup, Dikes)
        # --------------------------------------------
          
        # Save output to disk once in a while --------
        MTK_save_output(Grid, Arrays, Tracers, Dikes, time_props)
        # --------------------------------------------

        # Optionally Update arrays (such as T) -------
        MTK_update_Arrays!(Arrays, Grid, Num)
        # --------------------------------------------
        
        # Display output -----------------------------
        MTK_print_output(Grid, Num, Arrays, Mat_tup, Dikes)
        # --------------------------------------------
```
They are now set to default parameters (many are empty), but can be overwritten as:

```Julia
import MagmaThermoKinematics.MTK_GMG_2D.MTK_print_output
function MTK_print_output(Grid::GridData, Num::NumericalParameters, Arrays::NamedTuple, Mat_tup::Tuple, Dikes::DikeParameters)
    println("$(Num.it), max. temperature = $(maximum(Arrays.Tnew))")
    return nothing
end
```

2023-12-11 14:18 UTC, aelligp commented
For the longterm support it might be good to update the `deps` to the newest release of `Makie.jl` (v.0.20.x)

2023-12-13 15:05 UTC, albert-de-montserrat requested changes
Looks overall good to me. As a general comment, the examples are somewhat hard to read, some suggestions:

1. Remove all the commented lines
2. Don't use short hand branches. For example, dont write 
```julia
    if USE_GPU; Phases      =   CUDA.ones(Int64,Grid.N...)
    else        Phases      =   ones(Int64,Grid.N...)   end
```
but 
```julia
    if USE_GPU
        Phases  = CUDA.ones(Int64,Grid.N...)
    else 
        Phases   =  ones(Int64,Grid.N...)   
    end
```
3. Don't stack two lines of code into one. E.g. split this into two lines of code
```julia
if isdir("viz3D_out")==false mkdir("viz3D_out") end; loadpath = "./viz3D_out/"; pvd = paraview_collection("Example3D");
```
4. Try to tabulate the equal assignments of the same blocks. E.g. as in here
```julia
            x_1d =  Grid.coord1D[1]/1e3;
            z_1d =  Grid.coord1D[2]/1e3;
            temp_data = Array(Arrays.Tnew)'
            ϕ_data = Array(Arrays.ϕ)'
            phase_data = Float64.(Array(Arrays.Phases))'
```

2023-12-13 15:06 UTC, aelligp requested changes
Some minor things e.g. typos

2023-12-13 15:06 UTC, aelligp commented on test/test_MTK_GMG_2D.jl
> +Nz          =   135;
```suggestion
Nx          =   Num.Nx;  # resolution in x
Nz          =   Num.Nz;
```

2023-12-13 15:24 UTC, albert-de-montserrat commented on src/Diffusion.jl
> +    return
Actually `return` and `return nothing` are equivalent :)

2023-12-14 11:26 UTC, aelligp approved these changes

2023-12-14 12:03 UTC, merged